[package]
name = "eeprom_file_burner"
version = "0.1.0"
authors = ["Jay"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serlib = { path = "C:/Users/Jay/Major Projects/Rust/serlib" }
serial = "0.4"